apiVersion: apps/v1
kind: Deployment
metadata:
	name: mssql-deploy
	labels:
		name: mssql-deploy
		app: microservice-clean_arqui_api
spec:
	replicas: 1
	selector:
		matchLabels:
			app: microservice-clean_arqui_api
			name: mssql-pod
	template:
		metadata:
			name: mssql-pod
			labels:
				app: microservice-clean_arqui_api
				name: mssql-pod
		spec:
			containers:
				- name: mssql
				  image: mcr.microsoft.com/mssql/server
				  ports:
					- containerPort: 1433
				  env:
				  - name: ACCEPT_EULA
					value: "Y"
				  - name: SA_PASSWORD
					value: "$DFGServer181296"